name: App service containers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: markushtesti.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . --file dockerfile --tag markushtesti.azurecr.io/petclinic:${{ github.sha }}
        docker push markushtesti.azurecr.io/petclinic:${{ github.sha }}

    - uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'markushpetclinic'
        images: 'markushtesti.azurecr.io/petclinic:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
